name: Deploy Lambda Function

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Verify environment
      run: |
        echo "AWS CLI version: $(aws --version)"
        echo "Python version: $(python3 --version)"
        echo "Current directory: $(pwd)"
        echo "Files in directory: $(ls -la)"
    
    - name: Create deployment package (code only - using layers)
      run: |
        zip function.zip hs-list-teams-bot.py
        echo "Created deployment package:"
        ls -lh function.zip
    
    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name hs-list-teams-bot \
          --zip-file fileb://function.zip
        echo "✅ Lambda function updated successfully"
    
    - name: Verify deployment
      run: |
        aws lambda get-function \
          --function-name hs-list-teams-bot \
          --query 'Configuration.[FunctionName,Runtime,Handler,LastModified]' \